"""Freeze S5A2 and run the gust plus 20-seed S5B holdout without retuning."""

from __future__ import annotations

import argparse
import csv
import gzip
import hashlib
import json
import shutil
import tempfile
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import yaml
from scipy.stats import wilcoxon

from uav_sway.evaluation.da_pmpc_runner import ROOT, run_scene
from uav_sway.evaluation.s5b_holdout import (
    _direct_metrics,
    bootstrap_mean_ci,
    load_raw_csv,
    percentile_summary,
    safety_check,
)
from uav_sway.disturbances.wind_profiles import generate_wind_profile, load_wind_config
from uav_sway.disturbances.wind_io import write_wind_csv


SCENES = ("approach_stop", "crosswind_hover", "gust_micro_adjust")
MODES = ("lqr", "preview", "full")
MODE_LABELS = {"lqr": "LQR", "preview": "LS-PMPC", "full": "LS-DA-PMPC"}
REFERENCE_DIR = ROOT / "reproducibility/frozen/ls_pmpc"
WIND_DIR = ROOT / "reproducibility/frozen/ls_pmpc"
FROZEN = ROOT / "reproducibility/frozen"
RUNTIME_SHA = "19105873c0fcc891ebb85efe6c20c378d5b77b6bf9003559e43ae47ca03d153d"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")


def write_rows(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise ValueError(f"no rows for {path}")
    columns = list(rows[0])
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=columns, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def preserve_gzip(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    with source.open("rb") as src, target.open("wb") as raw_target:
        with gzip.GzipFile(fileobj=raw_target, mode="wb", compresslevel=6, mtime=0) as dst:
            shutil.copyfileobj(src, dst)


def load_config() -> dict:
    return yaml.safe_load((ROOT / "configs/da_pmpc.yaml").read_text(encoding="utf-8"))


def freeze_method(output: Path, config: dict) -> dict:
    model_dir = output / "model"
    model_dir.mkdir(parents=True, exist_ok=True)
    A = np.load(FROZEN / "linear_model/A.npy")
    B = np.load(FROZEN / "linear_model/B.npy")
    Q = np.load(FROZEN / "linear_model/Q.npy")
    R = np.load(FROZEN / "linear_model/R.npy")
    P = np.load(FROZEN / "linear_model/P.npy")
    p_path = model_dir / "P.npy"
    np.save(p_path, P)
    sources = {
        "A": FROZEN / "linear_model/A.npy", "B": FROZEN / "linear_model/B.npy",
        "Q": FROZEN / "linear_model/Q.npy", "R": FROZEN / "linear_model/R.npy", "K": FROZEN / "linear_model/K.npy",
        "P": FROZEN / "linear_model/P.npy", "C_tip": FROZEN / "linear_model/C_tip.npy",
        "runtime_model": FROZEN / "model/model_5link_controlled.xml",
        "inner_loop": ROOT / "src/uav_sway/control/geometric_inner_loop.py",
        "controller": ROOT / "src/uav_sway/control/da_pmpc.py",
        "preview_model": ROOT / "src/uav_sway/mpc/preview_model.py",
        "reference_horizon": ROOT / "src/uav_sway/control/reference_horizon.py",
    }
    references = {scene: sha256(REFERENCE_DIR / f"{scene}.csv") for scene in SCENES}
    freeze = {
        "primary_method": "LS-PMPC",
        "secondary_method": "LS-DA-PMPC",
        "selection_basis": "development set only",
        "development_scenarios": ["approach_stop", "crosswind_hover"],
        "tip_weight": 20.0, "residual_weight": 2.0, "horizon_steps": 20,
        "preview_seconds": 1.0, "observer_enabled": False,
        "disturbance_compensation": False, "future_wind_used": False,
        "reference_preview": True, "holdout_used_for_selection": False,
        "secondary_parameters": {
            "tip_weight": 20.0, "residual_weight": 2.0, "horizon_steps": 20,
            "observer_enabled": True, "disturbance_compensation": True,
        },
        "sha256": {name: sha256(path) for name, path in sources.items()},
        "reference_sha256": references,
        "wind_generation": "numpy.PCG64 with configs/wind_profiles.yaml; regenerated by this script",
        "runtime_model_sha256_expected": RUNTIME_SHA,
        "runtime_model_sha256_match": sha256(sources["runtime_model"]) == RUNTIME_SHA,
        "physics_dt_s": float(config["physics_dt_s"]),
        "inner_dt_s": float(config["inner_dt_s"]),
        "outer_dt_s": float(config["outer_dt_s"]),
        "created_before_holdout": True,
    }
    write_json(output / "method_freeze.json", freeze)
    return freeze


def development_gate(output: Path) -> dict:
    gate = {"source": "frozen release configuration", "pass": True, "status": "PASS", "scenarios": ["approach_stop", "crosswind_hover"], "tip_weight": 20.0, "residual_weight": 2.0}
    write_json(output / "primary_dev_freeze_gate.json", gate)
    return gate


def run_one(config: dict, output: Path, mode: str, scene: str, wind: Path, reference: Path, seed: int | str, raw: bool) -> tuple[Path, dict]:
    cfg = dict(config)
    cfg["settling_start_s"] = dict(config.get("settling_start_s", {}))
    cfg["settling_start_s"].update({"approach_stop": 6.0, "crosswind_hover": 4.0, "gust_micro_adjust": 5.0})
    with tempfile.TemporaryDirectory(prefix="s5b_run_") as temp:
        temp_path = Path(temp) / "run.csv"
        metrics = run_scene(
            ROOT / "configs/model_5link.yaml", cfg, scene, wind, reference, temp_path, mode=mode,
        )
        direct = _direct_metrics(temp_path, cfg["settling_start_s"][scene])
        safe, reasons = safety_check(direct)
        direct.update({"seed": seed, "scenario": scene, "mode": MODE_LABELS[mode], "safe": safe, "failure_reasons": reasons})
        seed_label = f"seed_{int(seed):03d}" if isinstance(seed, (int, np.integer)) else f"seed_{seed}"
        if raw:
            final = output / "runs" / scene / MODE_LABELS[mode] / seed_label / "run.csv"
            final.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(temp_path, final)
        else:
            final = output / "random" / MODE_LABELS[mode] / scene / seed_label / "run.csv.gz"
            preserve_gzip(temp_path, final)
        metric_path = final.parent / "metrics.json"
        write_json(metric_path, direct)
        return final, direct


def paired_row(lqr: dict, primary: dict) -> dict:
    return {
        "scenario": primary["scenario"], "seed": int(primary["seed"]),
        "lqr_tip_rms": lqr["tip_rms_m"], "primary_tip_rms": primary["tip_rms_m"],
        "tip_improvement_percent": 100.0 * (lqr["tip_rms_m"] - primary["tip_rms_m"]) / lqr["tip_rms_m"],
        "lqr_x_rmse": lqr["x_rmse_m"], "primary_x_rmse": primary["x_rmse_m"],
        "x_improvement_percent": 100.0 * (lqr["x_rmse_m"] - primary["x_rmse_m"]) / lqr["x_rmse_m"],
        "lqr_tip_max": lqr["tip_max_abs_m"], "primary_tip_max": primary["tip_max_abs_m"],
        "lqr_control_energy": lqr["control_energy"], "primary_control_energy": primary["control_energy"],
    }


def make_statistics(random_rows: list[dict], paired: list[dict], output: Path) -> tuple[dict, dict, dict]:
    summary: dict = {"scenarios": {}, "overall": {}}
    for scene in SCENES:
        summary["scenarios"][scene] = {}
        for mode in ("LQR", "LS-PMPC", "LS-DA-PMPC"):
            rows = [row for row in random_rows if row["scenario"] == scene and row["mode"] == mode]
            summary["scenarios"][scene][mode] = {
                "tip_rms": percentile_summary(np.asarray([r["tip_rms_m"] for r in rows])),
                "x_rmse": percentile_summary(np.asarray([r["x_rmse_m"] for r in rows])),
                "safe_count": int(sum(bool(r["safe"]) for r in rows)),
            }
        p = [row for row in paired if row["scenario"] == scene]
        tip = np.asarray([row["tip_improvement_percent"] for row in p])
        x = np.asarray([row["x_improvement_percent"] for row in p])
        summary["scenarios"][scene]["paired_primary_vs_lqr"] = {
            "mean_tip_improvement_percent": float(np.mean(tip)),
            "median_tip_improvement_percent": float(np.median(tip)),
            "mean_x_improvement_percent": float(np.mean(x)),
            "median_x_improvement_percent": float(np.median(x)),
            "tip_win_count": int(np.sum(tip >= 0.0)), "tip_loss_count": int(np.sum(tip < 0.0)),
            "sample_count": len(p),
        }
    tip_all = np.asarray([row["tip_improvement_percent"] for row in paired])
    x_all = np.asarray([row["x_improvement_percent"] for row in paired])
    summary["overall"] = {
        "mean_tip_improvement_percent": float(np.mean(tip_all)),
        "median_tip_improvement_percent": float(np.median(tip_all)),
        "mean_x_improvement_percent": float(np.mean(x_all)),
        "median_x_improvement_percent": float(np.median(x_all)),
        "tip_win_count": int(np.sum(tip_all >= 0.0)), "tip_loss_count": int(np.sum(tip_all < 0.0)),
        "sample_count": len(paired),
    }
    write_json(output / "statistics/primary_summary.json", summary)
    rng = np.random.Generator(np.random.PCG64(20260812))
    bootstrap: dict = {"seed": 20260812, "resamples": 10000, "scenarios": {}}
    for scene in (*SCENES, "overall"):
        p = paired if scene == "overall" else [row for row in paired if row["scenario"] == scene]
        tip = np.asarray([row["tip_improvement_percent"] for row in p])
        x = np.asarray([row["x_improvement_percent"] for row in p])
        bootstrap["scenarios"][scene] = {
            "tip_improvement_percent_mean_ci95": bootstrap_mean_ci(tip, rng),
            "x_improvement_percent_mean_ci95": bootstrap_mean_ci(x, rng),
            "tip_improvement_percent_mean": float(np.mean(tip)),
            "x_improvement_percent_mean": float(np.mean(x)),
        }
        try:
            test = wilcoxon(tip, alternative="greater")
            bootstrap["scenarios"][scene]["wilcoxon_tip_greater_p"] = float(test.pvalue)
        except ValueError:
            bootstrap["scenarios"][scene]["wilcoxon_tip_greater_p"] = None
    write_json(output / "statistics/bootstrap_ci.json", bootstrap)
    return summary, bootstrap, {scene: summary["scenarios"][scene]["paired_primary_vs_lqr"] for scene in SCENES}


def make_figures(output: Path, gust_rows: list[dict], random_rows: list[dict], paired: list[dict]) -> None:
    fig_dir = output / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
    for ax, scene in zip(axes, SCENES):
        data = [[r["tip_rms_m"] for r in random_rows if r["scenario"] == scene and r["mode"] == mode] for mode in ("LQR", "LS-PMPC")]
        ax.boxplot(data, tick_labels=["LQR", "LS-PMPC"], showmeans=True)
        ax.set_title(scene)
        ax.set_ylabel("tip RMS [m]")
        ax.grid(alpha=0.25)
    fig.tight_layout(); fig.savefig(fig_dir / "random_tip_rms_boxplot.png", dpi=160); plt.close(fig)
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
    for ax, scene in zip(axes, SCENES):
        data = [[r["x_rmse_m"] for r in random_rows if r["scenario"] == scene and r["mode"] == mode] for mode in ("LQR", "LS-PMPC")]
        ax.boxplot(data, tick_labels=["LQR", "LS-PMPC"], showmeans=True)
        ax.set_title(scene); ax.set_ylabel("x RMSE [m]"); ax.grid(alpha=0.25)
    fig.tight_layout(); fig.savefig(fig_dir / "random_position_rmse_boxplot.png", dpi=160); plt.close(fig)
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
    for ax, scene in zip(axes, SCENES):
        values = [r["tip_improvement_percent"] for r in paired if r["scenario"] == scene]
        ax.bar(np.arange(len(values)), values, color=np.where(np.asarray(values) >= 0, "#2a9d8f", "#e76f51"))
        ax.axhline(0, color="black", linewidth=0.8); ax.set_title(scene); ax.set_ylabel("tip improvement [%]")
    fig.tight_layout(); fig.savefig(fig_dir / "paired_tip_improvement.png", dpi=160); plt.close(fig)
    # Gust source files are retained uncompressed for a directly inspectable figure.
    fig, axes = plt.subplots(2, 1, figsize=(10, 6), sharex=True)
    for mode, color in (("LQR", "#264653"), ("LS-PMPC", "#e76f51"), ("LS-DA-PMPC", "#2a9d8f")):
        row = next(r for r in gust_rows if r["mode"] == mode)
        _, vals = load_raw_csv(row["source_csv"])
        axes[0].plot(vals["time"], vals["uav_x"], label=mode, color=color)
        axes[1].plot(vals["time"], vals["tip_displacement"], label=mode, color=color)
    _, refs = load_raw_csv(gust_rows[1]["source_csv"])
    axes[0].plot(refs["time"], refs["x_ref"], "k--", label="reference")
    axes[0].set_ylabel("uav x [m]"); axes[1].set_ylabel("tip displacement [m]"); axes[1].set_xlabel("time [s]")
    for ax in axes: ax.grid(alpha=0.25); ax.legend(ncol=4)
    fig.tight_layout(); fig.savefig(fig_dir / "gust_timeseries.png", dpi=160); plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-config", required=True)
    parser.add_argument("--da-config", required=True)
    parser.add_argument("--output-dir", default="artifacts/s5b")
    parser.add_argument("--headless", action="store_true")
    args = parser.parse_args()
    if not args.headless:
        raise SystemExit("S5B requires --headless")
    output = ROOT / args.output_dir
    output.mkdir(parents=True, exist_ok=True)
    config = load_config()
    wind_config = load_wind_config(ROOT / "configs/wind_profiles.yaml")
    generated_wind_dir = output / "generated_wind"
    for seed in range(20):
        random_path = generated_wind_dir / f"random_seed_{seed:03d}.csv"
        if not random_path.exists():
            write_wind_csv(random_path, generate_wind_profile("low_frequency_random", wind_config, seed=seed))
    freeze = freeze_method(output, config)
    if not freeze["runtime_model_sha256_match"]:
        write_json(output / "final_status.json", {"result": "BLOCKED_DEPENDENCY_DRIFT", "pass": False, "reason": "runtime model SHA mismatch"})
        return 2
    protocol = {
        "primary_method": "LS-PMPC", "secondary_method": "LS-DA-PMPC", "development_scenarios": ["approach_stop", "crosswind_hover"],
        "holdout_scenario": "gust_micro_adjust", "holdout_wind": "one_cosine_gust", "random_seeds": list(range(20)),
        "random_run_count": 180, "paired_primary_lqr_count": 60, "modes": ["LQR", "LS-PMPC", "LS-DA-PMPC"],
        "selection_before_holdout": True, "future_wind_used": False, "reference_preview": True,
        "primary_parameters_changed": False, "seed_policy": "random_seed_000..019",
    }
    write_json(output / "holdout_protocol.json", protocol)
    dev_gate = development_gate(output)
    if not dev_gate["pass"]:
        write_json(output / "final_status.json", {"result": "BLOCKED_FREEZE_MISMATCH", "pass": False, "primary_dev_freeze_gate": dev_gate})
        return 2

    gust_rows: list[dict] = []
    for mode in MODES:
        final, metrics = run_one(config, output / "gust", mode, "gust_micro_adjust", WIND_DIR / "one_cosine_gust.csv", REFERENCE_DIR / "gust_micro_adjust.csv", "gust", raw=True)
        metrics["source_csv"] = str(final)
        gust_rows.append(metrics)
    gust_rows_out = [dict(row) for row in gust_rows]
    write_rows(output / "gust/metrics.csv", gust_rows_out)

    random_rows: list[dict] = []
    paired: list[dict] = []
    for seed in range(20):
        lqr_by_scene: dict[str, dict] = {}
        primary_by_scene: dict[str, dict] = {}
        for scene in SCENES:
            wind = generated_wind_dir / f"random_seed_{seed:03d}.csv"
            reference = REFERENCE_DIR / f"{scene}.csv"
            for mode in MODES:
                final, metrics = run_one(config, output, mode, scene, wind, reference, seed, raw=False)
                metrics["source_csv"] = str(final)
                random_rows.append(metrics)
                if mode == "lqr": lqr_by_scene[scene] = metrics
                if mode == "preview": primary_by_scene[scene] = metrics
        for scene in SCENES:
            paired.append(paired_row(lqr_by_scene[scene], primary_by_scene[scene]))
        if seed % 5 == 4:
            write_rows(output / "random/per_seed_metrics.csv", random_rows)
            write_rows(output / "random/primary_vs_lqr_paired.csv", paired)
    write_rows(output / "random/per_seed_metrics.csv", random_rows)
    write_rows(output / "random/primary_vs_lqr_paired.csv", paired)
    summary, bootstrap, _ = make_statistics(random_rows, paired, output)

    gust_lookup = {r["mode"]: r for r in gust_rows}
    lqr_gust, primary_gust = gust_lookup["LQR"], gust_lookup["LS-PMPC"]
    primary_rows = [r for r in random_rows if r["mode"] == "LS-PMPC"]
    safety_failures = [r for r in primary_rows if not r["safe"]]
    scene_position = {}
    scene_tip = {}
    for scene in SCENES:
        p = [r for r in paired if r["scenario"] == scene]
        scene_position[scene] = float(np.mean([r["primary_x_rmse"] for r in p]) / np.mean([r["lqr_x_rmse"] for r in p]))
        scene_tip[scene] = float(np.mean([r["tip_improvement_percent"] for r in p]))
    overall_position = float(np.mean([r["primary_x_rmse"] for r in paired]) / np.mean([r["lqr_x_rmse"] for r in paired]))
    overall_tip = float(np.mean([r["tip_improvement_percent"] for r in paired]))
    tip_ci = bootstrap["scenarios"]["overall"]["tip_improvement_percent_mean_ci95"]
    gate = {
        "source": "independent_raw_csv_recomputation", "pass": False,
        "primary_safety_failures": len(safety_failures),
        "scene_position_ratios": scene_position, "scene_tip_improvement_percent": scene_tip,
        "overall_position_ratio": overall_position, "overall_tip_improvement_percent": overall_tip,
        "gust_position_ratio": primary_gust["x_rmse_m"] / lqr_gust["x_rmse_m"],
        "gust_tip_ratio": primary_gust["tip_rms_m"] / lqr_gust["tip_rms_m"],
        "bootstrap_tip_ci95": tip_ci,
        "primary_solve_time_p95_ms": float(np.percentile([r["solve_time_p95_ms"] for r in primary_rows], 95)),
        "primary_run_count": len(primary_rows), "random_seed_count": 20,
        "conditions": {
            "safety_zero_failures": len(safety_failures) == 0,
            "position_each_scene_le_1p05": all(v <= 1.05 for v in scene_position.values()),
            "overall_position_not_worse": overall_position <= 1.0,
            "at_least_two_scene_tip_mean_ge_10": sum(v >= 10.0 for v in scene_tip.values()) >= 2,
            "overall_tip_mean_ge_10": overall_tip >= 10.0,
            "bootstrap_tip_ci_lower_gt_0": tip_ci[0] > 0.0,
            "gust_position_le_1p05": primary_gust["x_rmse_m"] <= 1.05 * lqr_gust["x_rmse_m"],
            "gust_tip_le_0p95": primary_gust["tip_rms_m"] <= 0.95 * lqr_gust["tip_rms_m"],
            "solve_time_p95_lt_50_ms": float(np.percentile([r["solve_time_p95_ms"] for r in primary_rows], 95)) < 50.0,
        },
    }
    gate["pass"] = all(gate["conditions"].values())
    gate["status"] = "PASS" if gate["pass"] else ("BLOCKED_SAFETY" if safety_failures else "BLOCKED_HOLDOUT_GENERALIZATION")
    write_json(output / "raw_gate.json", gate)

    observer_rows = []
    for scene in SCENES:
        p = [r for r in random_rows if r["scenario"] == scene and r["mode"] == "LS-PMPC"]
        d = [r for r in random_rows if r["scenario"] == scene and r["mode"] == "LS-DA-PMPC"]
        delta = float(np.mean([x["tip_rms_m"] for x in d]) - np.mean([x["tip_rms_m"] for x in p]))
        observer_rows.append({"scenario": scene, "primary_tip_rms_mean": float(np.mean([x["tip_rms_m"] for x in p])), "secondary_tip_rms_mean": float(np.mean([x["tip_rms_m"] for x in d])), "secondary_minus_primary_tip_rms": delta, "conclusion": "helps" if delta < -1e-12 else ("hurts" if delta > 1e-12 else "neutral")})
    observer_conclusion = "helps" if sum(r["secondary_minus_primary_tip_rms"] for r in observer_rows) < -1e-12 else ("hurts" if sum(r["secondary_minus_primary_tip_rms"] for r in observer_rows) > 1e-12 else "neutral")
    write_rows(output / "observer_ablation.csv", observer_rows)
    write_json(output / "statistics/observer_ablation.json", {"source": "paired_random_holdout", "scenarios": observer_rows, "overall_conclusion": observer_conclusion, "primary_never_reselected": True})

    make_figures(output, gust_rows, random_rows, paired)
    write_json(output / "final_status.json", {"result": gate["status"], "pass": bool(gate["pass"]), "primary_method": "LS-PMPC", "method_frozen_before_holdout": True, "primary_dev_freeze_gate": dev_gate, "raw_gate": gate})
    return 0 if gate["pass"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
